services:
  - type: web
    name: emergency-triage
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: NEXT_PUBLIC_FHIR_SERVER
        value: https://hapi.fhir.org/baseR4
    healthCheckPath: /
    autoDeploy: true 