services:
  - type: web
    name: emergency-triage
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: fhir-service
    env: node
    buildCommand: cd fhir && npm install && npm run build
    startCommand: cd fhir && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FHIR_PORT
        value: 3001
      - key: FHIR_DATABASE_URL
        sync: false
    healthCheckPath: /fhir/metadata
    autoDeploy: true 